/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on 24/04/2010, 12:15:56
 */

package forum.client.ui;

import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Ilya
 */
public class StatusPanel extends javax.swing.JPanel {

    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
    }

   



  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        _name = new javax.swing.JLabel();
        _size = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _online = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)));
        setForeground(new java.awt.Color(255, 255, 153));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(610, 158));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 102));
        jSeparator1.setEnabled(false);
        jSeparator1.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Hello");

        _name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        _name.setForeground(new java.awt.Color(255, 153, 0));
        _name.setText("guest!");

        _size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _size.setForeground(new java.awt.Color(51, 51, 51));
        _size.setText("There are 0 online users:");

        _online.setColumns(20);
        _online.setEditable(false);
        _online.setRows(5);
        jScrollPane1.setViewportView(_online);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_name, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_size)
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_size)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _name;
    private javax.swing.JTextArea _online;
    private javax.swing.JLabel _size;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JTextArea get_Online() {
        return _online;
    }

    public JLabel get_Name() {
        return _name;
    }

    public JLabel get_Size() {
        return _size;
    }

    public JLabel abrakadabra() {
        return _size;
    }
}
